# Generated by Django 5.2.1 on 2026-07-13 14:56

import apps.accounts.models
import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.caminho_avatar, validators=[apps.accounts.validators.validar_imagem], verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False, help_text='Quando verdadeiro, o usuário é obrigado a definir uma nova senha no próximo acesso.', verbose_name='precisa trocar a senha'),
        ),
    ]
