# Generated by Django 5.2.1 on 2026-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_foto_usuario_precisa_trocar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='conselho',
            field=models.CharField(blank=True, help_text='Ex.: CRP 10/12345. Usado na assinatura dos registros do prontuário.', max_length=50, verbose_name='registro no conselho'),
        ),
    ]
