# Generated by Django 5.2.1 on 2026-08-22 02:01

import re

import apps.accounts.validators
from django.db import migrations, models

# Especialidades típicas de uma clínica multiprofissional infantojuvenil.
# Semeadas para a clínica já começar com uma lista útil (editável na tela).
SEED_ESPECIALIDADES = [
    "Psicólogo Clínico",
    "Neuropsicólogo",
    "Psicopedagogo",
    "Fonoaudiólogo",
    "Terapeuta Ocupacional",
    "Psiquiatra Infantil",
    "Psicomotricista",
    "Musicoterapeuta",
    "Fisioterapeuta",
    "Nutricionista",
    "Assistente Social",
    "Analista do Comportamento (ABA)",
]

TIPOS_CONSELHO = {"CRP", "CRM", "CREFONO", "CREFITO", "CRESS", "CRN", "CREF"}


def migrar_conselho_e_semear(apps, schema_editor):
    """Semeia especialidades e converte o ``conselho`` texto-livre em campos estruturados."""
    Usuario = apps.get_model("accounts", "Usuario")
    Especialidade = apps.get_model("accounts", "Especialidade")

    for nome in SEED_ESPECIALIDADES:
        Especialidade.objects.get_or_create(nome=nome)

    # Converte "CRP 10/12345" → tipo=CRP, numero="10/12345". Sem tipo reconhecido,
    # guarda o texto bruto no número para não perder o dado.
    for usuario in Usuario.objects.exclude(conselho="").exclude(conselho__isnull=True):
        texto = (usuario.conselho or "").strip()
        if not texto:
            continue
        tipo, resto = "", texto
        match = re.match(r"^([A-Za-z]+)\s*(.*)$", texto)
        if match and match.group(1).upper() in TIPOS_CONSELHO:
            tipo = match.group(1).upper()
            resto = match.group(2).strip()
        usuario.conselho_tipo = tipo
        usuario.conselho_numero = resto[:30]
        usuario.save(update_fields=["conselho_tipo", "conselho_numero"])


def remover_seed(apps, schema_editor):
    """Reverso: remove as especialidades semeadas que não têm profissionais vinculados."""
    Especialidade = apps.get_model("accounts", "Especialidade")
    Especialidade.objects.filter(
        nome__in=SEED_ESPECIALIDADES, profissionais__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_conselho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conselho_numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='número no conselho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conselho_tipo',
            field=models.CharField(blank=True, choices=[('CRP', 'CRP — Psicologia'), ('CRM', 'CRM — Medicina'), ('CREFONO', 'CREFONO — Fonoaudiologia'), ('CREFITO', 'CREFITO — Fisioterapia/T.O.'), ('CRESS', 'CRESS — Serviço Social'), ('CRN', 'CRN — Nutrição'), ('CREF', 'CREF — Educação Física'), ('OUTRO', 'Outro')], max_length=10, verbose_name='conselho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conselho_uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF do conselho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente dígitos. Opcional.', max_length=11, null=True, unique=True, validators=[apps.accounts.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado (UF)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='identidade (RG)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg_orgao_emissor',
            field=models.CharField(blank=True, max_length=20, verbose_name='órgão emissor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro')], max_length=10, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades do prestador (obrigatório para o papel PROFISSIONAL).', related_name='profissionais', to='accounts.especialidade', verbose_name='especialidades'),
        ),
        # Copia o conselho texto-livre para os campos estruturados e semeia as
        # especialidades — ANTES de remover o campo antigo (ordem importa).
        migrations.RunPython(migrar_conselho_e_semear, remover_seed),
        migrations.RemoveField(
            model_name='usuario',
            name='conselho',
        ),
    ]
