# Generated by Django 5.2.1 on 2026-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_especialidade_remove_usuario_conselho_usuario_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('DIRECAO', 'Direção'), ('SUPERVISAO', 'Supervisão'), ('PROFISSIONAL', 'Profissional'), ('RECEPCAO', 'Recepção'), ('FINANCEIRO', 'Financeiro')], max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('DIRECAO', 'Direção'), ('SUPERVISAO', 'Supervisão'), ('PROFISSIONAL', 'Profissional'), ('RECEPCAO', 'Recepção'), ('FINANCEIRO', 'Financeiro')], default='PROFISSIONAL', help_text='Papel principal (derivado do conjunto ``papeis`` por precedência). Mantido automaticamente; use ``papeis`` para atribuir múltiplos papéis.', max_length=20, verbose_name='papel principal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='papeis',
            field=models.ManyToManyField(blank=True, help_text='Todos os papéis do usuário (um usuário pode ter mais de um).', related_name='usuarios', to='accounts.papelusuario', verbose_name='papéis'),
        ),
    ]
