# Generated by Django 5.2.1 on 2026-07-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AusenciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('profissional', models.ForeignKey(limit_choices_to={'role': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='ausencias', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Ausência do profissional',
                'verbose_name_plural': 'Ausências dos profissionais',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('duracao_minutos', models.PositiveIntegerField(verbose_name='duração (minutos)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('profissional', models.ForeignKey(limit_choices_to={'role': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], db_index=True, verbose_name='dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='horário de início')),
                ('horario_fim', models.TimeField(verbose_name='horário de fim')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('profissional', models.ForeignKey(limit_choices_to={'role': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Disponibilidade do profissional',
                'verbose_name_plural': 'Disponibilidades dos profissionais',
                'ordering': ['profissional', 'dia_semana', 'horario_inicio'],
                'unique_together': {('profissional', 'dia_semana', 'horario_inicio')},
            },
        ),
    ]
