# Generated by Django 5.2.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("data", models.DateField(db_index=True, verbose_name="data")),
                ("horario_inicio", models.TimeField(verbose_name="horário de início")),
                ("horario_fim", models.TimeField(verbose_name="horário de fim")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADO", "Agendado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("REALIZADO", "Realizado"),
                            ("FALTA", "Falta"),
                        ],
                        db_index=True,
                        default="AGENDADO",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="observações"),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="pacientes.paciente",
                        verbose_name="paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        limit_choices_to={"role": "PROFISSIONAL"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profissional",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="clinica.sala",
                        verbose_name="sala",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agendamentos",
                        to="clinica.servico",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data", "horario_inicio"],
            },
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data", "profissional"], name="clinica_age_data_0a8f2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(fields=["data", "sala"], name="clinica_age_data_7c4b1e_idx"),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data", "paciente"], name="clinica_age_data_3d9f6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(fields=["status"], name="clinica_age_status_5e2c8b_idx"),
        ),
    ]
