# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_agendamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="parecer_status",
            field=models.TextField(
                blank=True,
                help_text="Obrigatório caso o status seja Faltou ou Cancelado.",
                null=True,
                verbose_name="Parecer/Justificativa do Status",
            ),
        ),
    ]
