# Generated by Django 5.2.1 on 2026-07-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_agendamento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='clinica_age_data_715743_idx',
            old_name='clinica_age_data_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='clinica_age_data_af5b25_idx',
            old_name='clinica_age_data_7c4b1e_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='clinica_age_data_ad2419_idx',
            old_name='clinica_age_data_3d9f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='clinica_age_status_1c14f0_idx',
            old_name='clinica_age_status_5e2c8b_idx',
        ),
    ]
