# Generated by Django 5.2.1 on 2026-07-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_agendamento_parecer_status'),
        ('clinica', '0003_rename_clinica_age_data_0a8f2d_idx_clinica_age_data_715743_idx_and_more'),
    ]

    operations = [
    ]
