# Generated by Django 5.2.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0004_merge_20260714_1918"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("data", models.DateField(db_index=True, verbose_name="data do atendimento")),
                (
                    "servico_nome",
                    models.CharField(max_length=150, verbose_name="nome do serviço"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor produzido"
                    ),
                ),
                ("motivo", models.CharField(max_length=100, verbose_name="motivo")),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producao",
                        to="clinica.agendamento",
                        verbose_name="agendamento",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producoes",
                        to="pacientes.paciente",
                        verbose_name="paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produção",
                "verbose_name_plural": "Produções",
                "ordering": ["-data"],
            },
        ),
    ]
