# Generated by Django 5.2.1 on 2026-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_data_rename_status_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('PRE_CONFIRMADO', 'Pré-confirmado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('FALTA', 'Falta'), ('DESMARCADO', 'Desmarcado')], db_index=True, default='AGENDADO', max_length=14, verbose_name='status'),
        ),
    ]
