# Generated by Django 5.2.1 on 2026-08-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_alterfield_status_agendamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='numero_na_serie',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número na série'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='parecer_status',
            field=models.TextField(blank=True, help_text='Obrigatório caso o status seja Falta ou Desmarcado.', null=True, verbose_name='Parecer/Justificativa do Status'),
        ),
        migrations.CreateModel(
            name='SerieRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('frequencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], max_length=10, verbose_name='frequência')),
                ('data_fim', models.DateField(verbose_name='data fim da recorrência')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_recorrentes', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Série recorrente',
                'verbose_name_plural': 'Séries recorrentes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='clinica.serierecorrente', verbose_name='série recorrente'),
        ),
    ]
