# Generated by Django 5.2.1 on 2026-08-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_producao'),
        ('clinica', '0008_servico_split_valor'),
    ]

    operations = [
    ]
