# Generated by Django 5.2.1 on 2026-08-15 13:35

from django.conf import settings
from django.db import migrations, models


def copiar_profissional_para_m2m(apps, schema_editor):
    """Preserva o vínculo existente: copia o FK ``profissional`` para o M2M."""
    Servico = apps.get_model('clinica', 'Servico')
    for servico in Servico.objects.all():
        if servico.profissional_id:
            servico.profissionais.add(servico.profissional_id)


def reverter_m2m_para_profissional(apps, schema_editor):
    """Rollback: usa o primeiro profissional do M2M para repopular o FK."""
    Servico = apps.get_model('clinica', 'Servico')
    for servico in Servico.objects.all():
        primeiro = servico.profissionais.first()
        if primeiro:
            servico.profissional_id = primeiro.pk
            servico.save(update_fields=['profissional'])


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_merge_0005_producao_0008_servico_split_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(limit_choices_to={'role': 'PROFISSIONAL'}, related_name='servicos', to=settings.AUTH_USER_MODEL, verbose_name='profissionais'),
        ),
        migrations.RunPython(
            copiar_profissional_para_m2m,
            reverter_m2m_para_profissional,
        ),
        migrations.RemoveField(
            model_name='servico',
            name='profissional',
        ),
    ]
