# Generated by Django 5.2.1 on 2026-08-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_remove_servico_profissional_servico_profissionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atendimento_finalizado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o atendimento foi finalizado (fim do cronômetro).', null=True, verbose_name='atendimento finalizado em'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atendimento_iniciado_em',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Momento em que o profissional iniciou o atendimento (início do cronômetro).', null=True, verbose_name='atendimento iniciado em'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('PRE_CONFIRMADO', 'Pré-confirmado'), ('CONFIRMADO', 'Confirmado'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ATENDIDO', 'Atendido'), ('FALTA', 'Falta'), ('DESMARCADO', 'Desmarcado')], db_index=True, default='AGENDADO', max_length=14, verbose_name='status'),
        ),
    ]
