# Generated by Django 5.2.1 on 2026-08-14 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0008_servico_split_valor'),
        ('pacientes', '0004_add_foto_nome_pais_cadastro_incompleto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_horario', models.TextField(blank=True, verbose_name='preferência de horário')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CONVERTIDO', 'Convertido'), ('RECUSADO', 'Recusado')], db_index=True, default='AGUARDANDO', max_length=10, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('agendamento_resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_fila', to='clinica.agendamento', verbose_name='agendamento gerado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fila_espera', to='pacientes.paciente', verbose_name='paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_espera', to=settings.AUTH_USER_MODEL, verbose_name='profissional preferido')),
            ],
            options={
                'verbose_name': 'Fila de espera',
                'verbose_name_plural': 'Fila de espera',
                'ordering': ['criado_em'],
            },
        ),
    ]
