# Generated by Django 5.2.1 on 2026-08-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_especialidade_remove_usuario_conselho_usuario_bairro_and_more'),
        ('fila_espera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filaespera',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fila_espera', to='accounts.especialidade', verbose_name='especialidade preferida'),
        ),
        migrations.AddField(
            model_name='filaespera',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
    ]
