# Generated by Django 5.2.1 on 2026-08-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0011_agendamento_atendimento_finalizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_google', models.EmailField(blank=True, help_text='E-mail da conta Google autorizada (para exibição).', max_length=254, verbose_name='e-mail da conta Google')),
                ('refresh_token_cifrado', models.TextField(verbose_name='refresh token (cifrado)')),
                ('access_token', models.TextField(blank=True, verbose_name='access token')),
                ('access_token_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='access token expira em')),
                ('scopes', models.TextField(blank=True, verbose_name='escopos concedidos')),
                ('calendar_id', models.CharField(default='primary', help_text='Calendário de destino no Google (padrão: agenda principal).', max_length=255, verbose_name='ID do calendário')),
                ('ativa', models.BooleanField(default=True, help_text='Quando desligada, os agendamentos deixam de ser enviados ao Google.', verbose_name='sincronização ativa')),
                ('conectada_em', models.DateTimeField(auto_now_add=True, verbose_name='conectada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_google', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Conta Google',
                'verbose_name_plural': 'Contas Google',
            },
        ),
        migrations.CreateModel(
            name='EventoGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=1024, verbose_name='ID do evento no Google')),
                ('ultima_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='última sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento_google', to='clinica.agendamento', verbose_name='agendamento')),
                ('conta', models.ForeignKey(help_text='Conta/calendário onde o evento foi criado.', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='google_agenda.contagoogle', verbose_name='conta Google')),
            ],
            options={
                'verbose_name': 'Evento no Google',
                'verbose_name_plural': 'Eventos no Google',
            },
        ),
    ]
