# Generated by Django 5.2.1 on 2026-07-15 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0004_merge_20260714_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Quando desligado, nenhuma confirmação automática é enviada.', verbose_name='envio ativo')),
                ('antecedencia_dias', models.PositiveSmallIntegerField(default=1, help_text='Quantos dias antes da consulta a confirmação é enviada (1 = véspera).', verbose_name='antecedência (dias)')),
                ('horario_disparo', models.TimeField(default=datetime.time(9, 0), help_text='Horário em que a confirmação é enviada no dia do disparo.', verbose_name='horário do disparo')),
                ('mensagem', models.TextField(default='Olá, {paciente}. Seu atendimento está agendado para {data} às {hora} com {profissional}. Responda SIM para confirmar ou NÃO para cancelar.', help_text='Texto exibido/usado no modo simulado. Marcadores: {paciente}, {data}, {hora}, {profissional}.', verbose_name='mensagem (prévia)')),
                ('template_meta_nome', models.CharField(blank=True, help_text='Nome do template aprovado no WhatsApp Cloud API (Meta).', max_length=100, verbose_name='template Meta (nome)')),
                ('template_meta_idioma', models.CharField(default='pt_BR', max_length=10, verbose_name='template Meta (idioma)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de confirmação',
                'verbose_name_plural': 'Configuração de confirmação',
            },
        ),
        migrations.CreateModel(
            name='MensagemConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone (E.164)')),
                ('destinatario_nome', models.CharField(blank=True, max_length=150, verbose_name='destinatário')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('LIDO', 'Lido'), ('ERRO', 'Erro'), ('RESPONDIDO_SIM', 'Confirmado pelo paciente'), ('RESPONDIDO_NAO', 'Cancelado pelo paciente')], db_index=True, default='PENDENTE', max_length=20, verbose_name='status')),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='id da mensagem (Meta)')),
                ('resposta_texto', models.CharField(blank=True, max_length=255, verbose_name='resposta recebida')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='clinica.agendamento', verbose_name='agendamento')),
            ],
            options={
                'verbose_name': 'Mensagem de confirmação',
                'verbose_name_plural': 'Mensagens de confirmação',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['telefone', '-criado_em'], name='whatsapp_me_telefon_3ee026_idx'), models.Index(fields=['status'], name='whatsapp_me_status_937f3c_idx')],
            },
        ),
    ]
