# Generated by Django 5.2.1 on 2026-08-22 03:47

import apps.pacientes.validators
import apps.prontuario.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_especialidade_remove_usuario_conselho_usuario_bairro_and_more'),
        ('clinica', '0011_agendamento_atendimento_finalizado_em_and_more'),
        ('pacientes', '0005_paciente_rg_paciente_rg_orgao_emissor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItemProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_prontuario', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Categoria de prontuário',
                'verbose_name_plural': 'Categorias de prontuário',
                'ordering': ['profissional', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EntradaProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('conteudo', models.TextField(blank=True, help_text='Texto rico (itens FIXO/TEXTO_LIVRE).', verbose_name='conteúdo')),
                ('respostas', models.JSONField(blank=True, default=dict, help_text='Respostas por campo (itens FORMULARIO): {campo_id: valor}.', verbose_name='respostas')),
                ('schema_snapshot', models.JSONField(blank=True, default=list, help_text='Cópia do schema do item no momento do preenchimento.', verbose_name='schema no preenchimento')),
                ('data_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Quando o atendimento/evento ocorreu (pode diferir do registro).', verbose_name='data do evento')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_prontuario', to='clinica.agendamento', verbose_name='agendamento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_prontuario_autoradas', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='pacientes.paciente', verbose_name='paciente')),
                ('profissional', models.ForeignKey(blank=True, help_text='Dono da configuração do item (denormalizado para filtros).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_prontuario', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
                ('referente_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes', to='prontuario.entradaprontuario', verbose_name='referente a')),
            ],
            options={
                'verbose_name': 'Entrada do prontuário',
                'verbose_name_plural': 'Entradas do prontuário',
                'ordering': ['-data_evento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(upload_to=apps.prontuario.models.caminho_anexo_entrada, validators=[apps.pacientes.validators.validar_arquivo], verbose_name='arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='nome do arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_prontuario_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='prontuario.entradaprontuario', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'Anexo da entrada',
                'verbose_name_plural': 'Anexos da entrada',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GrupoExames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('exames', models.JSONField(blank=True, default=list, help_text='Lista de exames: [{nome, observacao}].', verbose_name='exames')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_exames', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Grupo de exames',
                'verbose_name_plural': 'Grupos de exames',
                'ordering': ['profissional', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('tipo_item', models.CharField(choices=[('FIXO', 'Item fixo'), ('TEXTO_LIVRE', 'Texto livre'), ('FORMULARIO', 'Formulário personalizado')], max_length=20, verbose_name='tipo do item')),
                ('chave_fixa', models.CharField(blank=True, help_text='Preenchido apenas para itens fixos do sistema.', max_length=40, verbose_name='chave do item fixo')),
                ('visivel', models.BooleanField(default=True, help_text='Liga/desliga a exibição do item (usado nos itens fixos).', verbose_name='visível')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('formulario_schema', models.JSONField(blank=True, default=list, help_text='Lista de campos {id, tipo, rotulo, ordem, obrigatorio, opcoes}.', verbose_name='schema do formulário')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='prontuario.categoriaitemprontuario', verbose_name='categoria')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_prontuario', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Item de prontuário',
                'verbose_name_plural': 'Itens de prontuário',
                'ordering': ['profissional', 'ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='entradaprontuario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='prontuario.itemprontuario', verbose_name='item'),
        ),
        migrations.CreateModel(
            name='ModeloAtestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome do modelo')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título impresso')),
                ('corpo', models.TextField(help_text='Texto do atestado com macros entre colchetes.', verbose_name='corpo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_atestado', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Modelo de atestado',
                'verbose_name_plural': 'Modelos de atestado',
                'ordering': ['profissional', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('corpo_resolvido', models.TextField(verbose_name='corpo resolvido')),
                ('cids', models.JSONField(blank=True, default=list, help_text='Lista de CIDs usados: [{codigo, descricao}].', verbose_name='CIDs')),
                ('emitido_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='emitido em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados', to='clinica.agendamento', verbose_name='agendamento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='pacientes.paciente', verbose_name='paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_prontuario', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados', to='prontuario.modeloatestado', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'Atestado',
                'verbose_name_plural': 'Atestados',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloProntuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('tipo_item', models.CharField(choices=[('FIXO', 'Item fixo'), ('TEXTO_LIVRE', 'Texto livre'), ('FORMULARIO', 'Formulário personalizado')], default='FORMULARIO', max_length=20, verbose_name='tipo do item')),
                ('formulario_schema', models.JSONField(blank=True, default=list, verbose_name='schema do formulário')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_prontuario', to='accounts.especialidade', verbose_name='especialidade')),
            ],
            options={
                'verbose_name': 'Protocolo pronto',
                'verbose_name_plural': 'Protocolos prontos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TextoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('compartilhado', models.BooleanField(default=False, help_text='Se verdadeiro, todos os profissionais podem usar este texto.', verbose_name='compartilhado com a equipe')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_padrao', to='prontuario.itemprontuario', verbose_name='item associado')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos_padrao', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'Texto padrão',
                'verbose_name_plural': 'Textos padrão',
                'ordering': ['profissional', 'ordem', 'titulo'],
            },
        ),
        migrations.AddIndex(
            model_name='itemprontuario',
            index=models.Index(fields=['profissional', 'ativo'], name='prontuario__profiss_2631d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemprontuario',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_fixa', ''), _negated=True), fields=('profissional', 'chave_fixa'), name='item_fixo_unico_por_profissional'),
        ),
        migrations.AddIndex(
            model_name='entradaprontuario',
            index=models.Index(fields=['paciente', '-data_evento'], name='prontuario__pacient_e7d2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaprontuario',
            index=models.Index(fields=['item'], name='prontuario__item_id_5d8645_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaprontuario',
            index=models.Index(fields=['profissional'], name='prontuario__profiss_28e7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='atestado',
            index=models.Index(fields=['paciente', '-emitido_em'], name='prontuario__pacient_e6ccbd_idx'),
        ),
    ]
