# Generated by Django 5.2.1 on 2026-08-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('OBSERVACAO', 'Observação'), ('COMENTARIO', 'Comentário')], default='COMENTARIO', max_length=10, verbose_name='tipo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_prontuario', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='prontuario.entradaprontuario', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'Anotação da entrada',
                'verbose_name_plural': 'Anotações da entrada',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['entrada', 'tipo', 'criado_em'], name='prontuario__entrada_aa8b4b_idx')],
            },
        ),
    ]
