# Generated by Django 5.2.1 on 2026-07-13 13:53

import apps.pacientes.models
import apps.pacientes.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(db_index=True, max_length=150, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(blank=True, help_text='Somente dígitos. Opcional (pacientes infantojuvenis podem não ter).', max_length=11, null=True, unique=True, validators=[apps.pacientes.validators.validar_cpf], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado (UF)')),
                ('informacoes_complementares', models.TextField(blank=True, verbose_name='informações complementares')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('profissionais', models.ManyToManyField(blank=True, help_text='Profissionais que atendem este paciente.', limit_choices_to={'is_active': True, 'role__in': ['PROFISSIONAL', 'SUPERVISAO', 'DIRECAO']}, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='profissionais responsáveis')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.pacientes.models.caminho_documento, validators=[apps.pacientes.validators.validar_arquivo], verbose_name='arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='nome do arquivo')),
                ('tipo', models.CharField(choices=[('DOCUMENTO_PESSOAL', 'Documento pessoal'), ('SOLICITACAO_MEDICA', 'Solicitação médica'), ('RELATORIO', 'Relatório'), ('LAUDO', 'Laudo'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='tipo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Documento do paciente',
                'verbose_name_plural': 'Documentos do paciente',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('parentesco', models.CharField(choices=[('MAE', 'Mãe'), ('PAI', 'Pai'), ('AVO', 'Avó/Avô'), ('TIO', 'Tia/Tio'), ('TUTOR', 'Tutor(a) legal'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='parentesco')),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[apps.pacientes.validators.validar_cpf], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('principal', models.BooleanField(default=False, help_text='Responsável usado por padrão para contatos e avisos.', verbose_name='contato principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['-principal', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nome_completo'], name='pacientes_p_nome_co_d53042_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['ativo'], name='pacientes_p_ativo_111950_idx'),
        ),
    ]
