# Generated by Django 5.2.1 on 2026-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_normaliza_telefone_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alertas',
            field=models.CharField(blank=True, help_text='Avisos importantes (ex.: alergias, cuidados). Destacado no prontuário.', max_length=255, verbose_name='alertas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cid',
            field=models.CharField(blank=True, help_text='Código CID relacionado (ex.: F90.0).', max_length=20, verbose_name='CID'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='diagnóstico / hipótese diagnóstica'),
        ),
    ]
