# Generated by Django 5.2.1 on 2026-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_alertas_paciente_cid_paciente_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cadastro_incompleto',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado quando o paciente foi criado com dados mínimos durante o agendamento.', verbose_name='cadastro incompleto'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/%Y/%m/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome da mãe'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome do pai'),
        ),
    ]
