# Generated by Django 5.2.1 on 2026-08-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_add_foto_nome_pais_cadastro_incompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg_orgao_emissor',
            field=models.CharField(blank=True, max_length=20, verbose_name='órgão emissor do RG'),
        ),
    ]
