# Generated by Django 5.2.1 on 2026-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_rg_paciente_rg_orgao_emissor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='escola',
            field=models.CharField(blank=True, max_length=150, verbose_name='escola'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escola_responsavel_nome',
            field=models.CharField(blank=True, help_text='Pessoa de contato na escola (coordenação, professor(a), etc.).', max_length=150, verbose_name='responsável na escola'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escola_responsavel_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone do responsável na escola'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='serie_escolar',
            field=models.CharField(blank=True, help_text='Ex.: Maternal, 3º ano do fundamental, 1ª série do médio.', max_length=50, verbose_name='série escolar'),
        ),
    ]
