# Generated by Django 5.2.1 on 2026-08-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_escola_paciente_escola_responsavel_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='serie_escolar',
            field=models.CharField(blank=True, choices=[('BERCARIO', 'Berçário'), ('MATERNAL', 'Maternal'), ('PRE_1', 'Pré I (Jardim I)'), ('PRE_2', 'Pré II (Jardim II)'), ('EF_1', '1º ano — Fundamental'), ('EF_2', '2º ano — Fundamental'), ('EF_3', '3º ano — Fundamental'), ('EF_4', '4º ano — Fundamental'), ('EF_5', '5º ano — Fundamental'), ('EF_6', '6º ano — Fundamental'), ('EF_7', '7º ano — Fundamental'), ('EF_8', '8º ano — Fundamental'), ('EF_9', '9º ano — Fundamental'), ('EM_1', '1ª série — Médio'), ('EM_2', '2ª série — Médio'), ('EM_3', '3ª série — Médio')], max_length=20, verbose_name='série escolar'),
        ),
    ]
