# Generated by Django 5.2.1 on 2026-09-12 14:30

import apps.pacientes.models
import apps.pacientes.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_paciente_serie_escolar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='profissionais',
            field=models.ManyToManyField(blank=True, help_text='Profissionais que atendem este paciente.', limit_choices_to={'is_active': True, 'papeis__codigo__in': ['PROFISSIONAL', 'SUPERVISAO', 'DIRECAO']}, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='profissionais responsáveis'),
        ),
        migrations.CreateModel(
            name='NotaFiscalPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.pacientes.models.caminho_nota_fiscal, validators=[apps.pacientes.validators.validar_arquivo_nota_fiscal], verbose_name='arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='nome do arquivo')),
                ('data_emissao', models.DateField(db_index=True, verbose_name='data de emissão')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='pacientes.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Nota fiscal do paciente',
                'verbose_name_plural': 'Notas fiscais do paciente',
                'ordering': ['-data_emissao', '-criado_em'],
            },
        ),
    ]
