# Generated by Django 5.2.1 on 2026-08-14 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0008_servico_split_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CONVENIO', 'Convênio')], max_length=15, verbose_name='forma de pagamento')),
                ('valor_repasse_calculado', models.DecimalField(decimal_places=2, help_text='Snapshot do repasse do serviço no momento da baixa.', max_digits=10, verbose_name='repasse calculado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='clinica.agendamento', verbose_name='agendamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
